---
title: "Test Error Project 2 - Leader Board"
author: ""
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: html_document
---

```{r, label = "SETUP", echo = FALSE, results= 'hide', message = FALSE, warning = FALSE}
set.seed(389)
library(knitr)
knitr::opts_chunk$set(comment = NA, fig.show = 'as.is', fig.height = 4, fig.width = 4, prompt = TRUE, highlight = TRUE, tidy = FALSE, warning = FALSE, message = FALSE, tidy.opts=list(blank = TRUE, width.cutoff= 75, cache = TRUE))
```


```{r, echo = FALSE}
APRICE <- read.csv("price.csv")
#########################################################################
#
#Doe_John <- read.csv("Doe_John.csv")
#DoeJohn <- sqrt(mean((Doe_John$x - APRICE$price)^2))
#names(DoeJohn) <- "DoeJohn"
#


### You should at least beat what I gave to start with
yourlastname_yourfirstname <- read.csv("yourlastname_yourfirstname.csv")
BeatThis <- sqrt(mean((yourlastname_yourfirstname$x - APRICE$price)^2))
names(BeatThis) <- "BeatThis"

#
Balesky_Andrew <- read.csv("Balesky_Andrew.csv")
BaleskyAndrew  <- sqrt(mean((Balesky_Andrew$x - APRICE$price)^2))
names(BaleskyAndrew) <- "BaleskyAndrew"


bassett_keriann <- read.csv("bassett_keriann.csv")
bassettkeriann<- sqrt(mean((bassett_keriann$x - APRICE$price)^2))
names(bassettkeriann) <- "bassettkeriann"

Williams_kai <- read.csv("Williams_kai.csv")
Williamskai<- sqrt(mean((Williams_kai$x - APRICE$price)^2))
names(Williamskai) <- "Williamskai"


Fisher_Natalie <- read.csv("Fisher_Natalie.csv")
FisherNatalie  <- sqrt(mean((Fisher_Natalie$x - APRICE$price)^2))
names(FisherNatalie ) <- "FisherNatalie"


Whalen_Peter <- read.csv("Whalen_Peter.csv")
WhalenPeter<- sqrt(mean((Whalen_Peter$x - APRICE$price)^2))
names(WhalenPeter) <- "WhalenPeter"

Guinn_Bronson <- read.csv("Guinn_Bronson.csv")
GuinnBronson<- sqrt(mean((Guinn_Bronson$x - APRICE$price)^2))
names(GuinnBronson) <- "GuinnBronson"


#Gummow_Lucy-2<- read.csv("Gummow_Lucy-2")
#GummowLucy-2<- sqrt(mean((Gummow_Lucy-2$x - APRICE$price)^2))
#names(GummowLucy-2) <- "GummowLucy-2"

Leswing_Derek <- read.csv("Leswing_Derek.csv")
LeswingDerek <- sqrt(mean((Leswing_Derek$x - APRICE$price)^2))
names(LeswingDerek) <- "LeswingDerek"


Stetson_Cole <- read.csv("Stetson_Cole.csv")
StetsonCole <- sqrt(mean((Stetson_Cole$x - APRICE$price)^2))
names(StetsonCole) <- "StetsonCole"

Moodie_Chad <- read.csv("Moodie_Chad.csv")
MoodieChad  <- sqrt(mean((Moodie_Chad$x - APRICE$price)^2))
names(MoodieChad) <- "MoodieChad "

Lauver_Camden <- read.csv("Lauver_Camden.csv")
LauverCamden <- sqrt(mean((Lauver_Camden$x - APRICE$price)^2))
names(LauverCamden) <- "LauverCamden"

White_Cassidy <- read.csv("White_Cassidy.csv")
WhiteCassidy <- sqrt(mean((White_Cassidy$x - APRICE$price)^2))
names(WhiteCassidy) <- "WhiteCassidy"

Colella_Joseph<- read.csv("Colella_Joseph.csv")
ColellaJoseph <- sqrt(mean((Colella_Joseph$x - APRICE$price)^2))
names(ColellaJoseph) <- "ColellaJoseph"

Keith_Alan<-read.csv("Keith_Alan.csv")
KeithAlan <- sqrt(mean((Keith_Alan$x - APRICE$price)^2))
names(KeithAlan) <- "KeithAlan"

Gummow_Lucy<-read.csv("Gummow_Lucy.csv")
GummowLucy<- sqrt(mean((Gummow_Lucy$x - APRICE$price)^2))
names(GummowLucy) <- "GummowLucy"

```


```{r, echo = FALSE}
Leader <- data.frame(SMSPE = c(BeatThis,BaleskyAndrew,bassettkeriann,Williamskai,FisherNatalie,WhalenPeter,GuinnBronson,LeswingDerek,StetsonCole,MoodieChad,LauverCamden,WhiteCassidy,ColellaJoseph,KeithAlan,GummowLucy))
#ReyesRoberto,SmithDylan,PalmerLogan,SherrillPayce, #LivesayGabrielle,JohnsonGavin,GregoryMorgan,ethersonchristian,PerusoAlicia,spenceramelia,ReeseNoah ))

```

```{r, echo = FALSE}
#Leader <- data.frame(SMSPE = c(BeatThis, AllenWill, CampbellMax, VandenbergAndrew, DubeWill))
```

```{r, echo = FALSE}
knitr::kable(Leader[order(Leader$SMSPE), , drop = FALSE], col.names = "$\\sqrt{MSPE}$", align = "l")
```