---
title: "STT3851 Homework 3"
author: "Dr. Hasthika Rupasinghe"
date: Due -- September ?
output: 
    pdf_document: default
    html_document:
      keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1) We have data from the questionnaires survey (to ask people opinion) and objective testing with two attributes (acid durability and strength)
to classify whether a special paper tissue is good or not. Here is four training samples

THIS IS SAVED ON THE DESKTOP




NOT DONE: 4) Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods
towards more flexible approaches. The x-axis should represent
the amount of flexibility in the method, and the y-axis should
represent the values for each curve. There should be five curves.
Make sure to label each one.
(b) Explain why each of the five curves has the shape displayed in
part (a)