---
title: "Assignments STT 3851 - Spring2021"
author: "Dr. Lasanthi Watagoda"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    toc: true
    css: "../CSS/style.css"
---

***

**Jan 19:**

* Go over syllabus.
* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.
* [Chapter 1 - Introduction to Statistical Learning](../LectureNotesSp2021/Chapter1.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/TubZpEsgB2_XEgW7lMm-CrGfhLW3qd38Lm-0aSDJxe5TsGZpb03sy6LiVxXMcFQE.u4WtYhrRbq8gLeeQ)


***

<!--
* Sign-up for free accounts on [GitHub](https://github.com) and [Rpubs](https://rpubs.com).
* When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **first_name_last_name** as your username when you register with GitHub.  For example, my username on GitHub is *lasanthiwatagoda*. If you have a popular name such as John Smith, you may need to provide some other distinquishing characteristic in your username.  Please use the same **username** for your account on Rpubs. 
* Once you have a GitHub account, send an email to lasanthi@appstate.edu with a Subject line of **STT3851 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  I will then manually add you as a team member to the repository in the Lasanthi-ASU organization that has your name (**Last_name-First_name**).  This repository will be where you store all of your work for this course.  I will also change your repository to a private repository.

* [Statistics Review](../Rmarkdown/StatReview.html)--- take notes
* Homework: 
    + Read [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)
    
    ```{block2, note-text, type='rmdnote'}
 Most due dates are 5 p.m. Friday for assignments.

```  
-->


**Jan 21:**

* Before class:
    + Read chapter 1 [ISLR](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)
    + Watch [Opening Remarks and Examples](https://www.youtube.com/watch?v=2wLfFB_6SKI) (18:18)
    + Watch [Supervised and Unsupervised Learning](https://www.youtube.com/watch?v=LvaTokhYnDw)
  
* [Chapter 1 - Introduction to Statistical Learning](../LectureNotesSp2021/Chapter1.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/mdNgULvakbQHepiCYE7ilNqUhzmfRAHE5Ba9dFZUIcY0AaqzipH1vX1lPdqgzZfy.Try1DYm6otXhZliA)



***

**Jan 26:**

* Before class:
    + Read chapter 2 [ISLR](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)
    + Watch [Statistical Learning and Regression](https://www.youtube.com/watch?v=WjyuiK5taS8) (11:41)

* [Chapter 2 - Statistical Learning](../LectureNotesSp2021/Chapter2.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/Cn4tP75My8UjMm9emXMc1pmKtw00ctdTxJIr3ZhEckKSwSByc_REMsnSJ5edYJZy.dj7DMPzdgnJ3UXHF)


***
<!--
* Before class:
    + Read/review [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)
    + Read the [Git and GitHub](http://r-pkgs.had.co.nz/git.html) chapter from Hadley Wickham's book [R Packages](http://r-pkgs.had.co.nz/)
    
* Follow the directions from [Happy Git and GitHub for the useR](http://happygitwithr.com/) to [Introduce yourself to Git](http://happygitwithr.com/hello-git.html), [Connect to GitHub](http://happygitwithr.com/push-pull-github.html), and [Cache credentials for HTTPS](http://happygitwithr.com/credential-caching.html).

* Read/review Chapters 1-2 of [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
-->



**Jan 28:**

<!--* Before class:
    + [Watch Managing Change with RStudio]( https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-managing-change-part-1/) (37 minutes)-->
* Before class:
    + Watch [Curse of Dimensionality and Parametric Models](https://www.youtube.com/watch?v=UvxHOkYQl8g) (11:40)
    
* [Chapter 2 - Statistical Learning](../LectureNotesSp2021/Chapter2.html) --- Take notes in Rmarkdown

* In class **quiz 01**



* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/ll_gcPVyBDhO6UKYKViHdKTZqwNltT-XIBxF30CBc0OjSzU5Dv-kmo0RX1cBk-V2.fu9mEyvu90MjOOuU)

***




**Feb 02:**

* Before class:
    + Watch [Assessing Model Accuracy and Bias-Variance Trade-off](https://www.youtube.com/watch?v=VusKAosxxyk) (10:04)

* [Chapter 2 - Statistical Learning](../LectureNotesSp2021/Chapter2.html) --- Take notes in Rmarkdown

* Start [Chapter 02 Lab](../Labs/LabChap2.html) today

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/Vmv4GKpLtlyObWV17IN09wgmMmcE8_o6eYFajPRSvSULUOlaH02Vgz52sgJmxcDe.Muhkr-7se8H-j6Ur)

***

**Feb 04:**



* [Chapter 2 - Statistical Learning](../LectureNotesSp2021/Chapter2.html) --- Take notes in Rmarkdown

* Continue to work on [Chapter 02 Lab](../Labs/LabChap2.html) 

* In class **quiz 02**

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/wGqfU4x_Y4euRfiRZsRS5HO-MhYAwc45yo2t8M4qsYEsOUCuGQveuxAaHmlPG-cE.Dikhr6InwyYnX6wz)


***

**Feb 9:**

* [Chapter 2 - Statistical Learning](../LectureNotesSp2021/Chapter2.html) --- Take notes in Rmarkdown
* [Bias-Variance Trade-Off](https://lasanthi-asu.github.io/STT3851ClassRepo/LectureNotesSp2021/BiasVariance.html)
* Continue to work on [Chapter 02 Lab](../Labs/LabChap2.html) 

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/kC3Y2kJjSMho35N3lBrG8v5IHL65IylbKyy4p4Demr2wsyVShKH7v9jjb82xJ8ZI.9NwLOvTGNX06rtYE)

***

**Feb 11:**


* Before class:
    + Refer to [_bookdown: Authoring Books and Technical Documents with R Markdown_](https://bookdown.org/yihui/bookdown/) as needed


* [Chapter 02 Lab](../Labs/LabChap2.html) Due Sunday.

* In class **quiz 03**

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/RU-cKQYo27N_7ckALqeYICzXlFth6yilkBq99N2-MvKq3zXNdbp4Poi04PXehEo.wx3avop7NdR60wZP)
```{block,  type='rmdoptional'}
**Lab 02**

* Start: Reproduce [Lab: Modified Introduction To R](../Labs/LabChap2.html).  

* Submit your html file and Rmd file **Lab 2**, no later than 5 pm Feb 14th.

```


***

**Feb 16:**

* Before class:
    + Read pages 59-82 of [ISLR](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)
    + Watch [Simple Linear Regression and Confidence Intervals](https://www.youtube.com/watch?v=PsE9UqoWtS4) (13:01)


* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/thafhbKpP_tCLlgS1wrqy8oGtA_hMtBpSBOPZBuQiCQ-ZCLVSFzAHjbS-kFJzz4t.3WEoDV_QuHxebIMB)

***


**Feb 18:**

* Before class:
    + Watch [Hypothesis Testing ](https://www.youtube.com/watch?v=J6AdoiNUyWI) (8:24)
    + Watch [Multiple Linear Regression and Interpreting Regression Coefficients ](https://www.youtube.com/watch?v=1hbCJyM9ccs) (15:38)
<!--* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)

* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown


* In class **quiz 04**

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/4UPcBZ8wO6vJ2pBGMdmVhoiKYr4idG_4pY80cvc6GaA1R5OQJohDvmcHdsKo5vI.Z0NVNCMN_yyR0lgX)

***

**Feb 23:**

* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/a99-aTQt03w9OdvdjAdwNLx0WKkr1twgVjdIsn-8SZpL5yrtUxAx8OYcN9hKledn.rc_HKbXr2iOGqCbe)

***

**Feb 25:**

* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown

* In class **quiz 05**

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/pDuWKHPTLom8N1e6vWI6lz919QKfQDKWeJAHGHAfRJz_VbwWy3urrJoC3hqq-dHE.pCk5nhwL31sTonX1)

<!--

```{block,  type='rmdoptional'}
**Lab 03**

* Start: Reproduce [Lab: Linear Regression](../Rmarkdown/LabChap3.html).  

* Submit your **Lab 3** html file and Rmd file, no later than 5 pm March 7th.

```



```{block, startLab1, type='rmdoptional'}
**Lab 01**

* Start: Reproduce [Writing Assignment](../Rmarkdown/WritingAssignment.html).  

* Submit your html file to github **Lab 1** folder, no later than 5 pm Feb 21.

```

-->

***

**March 2:**

* Before class:
    + Watch [Lab: Linear Regression](https://www.youtube.com/watch?v=5ONFqIk3RFg) (22:10)
    
* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/bPLJtIFlomQx9ZFRVDO0mMwQ2IXsDbbqI3rhMimcoB8VxrVcCxUPkPywT3XHhcjt.7bvUY0k30cOvZ93A)

***

**March 4:**

* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/nvoYewLx4-UVoNJdFbYav6w-ZiSZFMGJJM1jaGHBx6dUCuwtwgfuEStUOpTc3RW0.Dz2gOrUywZB1JZfw)

```{block,  type='rmdoptional'}
**Chapter 3 Lab**

* Start: Reproduce [Lab: Linear Regression](../Labs/LabChap3.html).  

* Submit your **Chapter 3 Lab** html file and the Rmd file, no later than 5 pm March 24th.

```

***


**March 09:**

* Before class:

  + Read pages 82-120 [ISLR](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)
    + Watch [Model Selection and Qualitative Predictors](https://www.youtube.com/watch?v=3T6RXmIHbJ4) (14:51)
    
* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/3DMaalegF6YDexLknJHEbCoRQiR1nkw2P0gCGumPW6vatiaMAu5bZo-SyGd-dDaI.IEmIjRV-UCPEK3pF)

***

**March 11:**

* Before class:

    + Watch [Interactions and Nonlinearity](https://www.youtube.com/watch?v=IFzVxLv0TKQ) (14:16)
    
* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown
    
* In class **quiz 06**

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/8hgkYFrRi4RWAHCwK8tqxBXNKGfNKxiusazWe3o2xGVQYH4MczQ8885QhJS01u7D.bmQRkTSG3al5rQOe)


***


**Mar 16:**

* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown



```{block,  type='rmdoptional'}
**Reminder: Chapter 3 Lab**

* Keep working on: Reproduce [Lab: Linear Regression](../Labs/LabChap3.html).  

* Submit your **Chapter 3 Lab** html file and the Rmd file, no later than 5 pm March 24th.

```


* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/lJENxX6ROgh0rzsSy6KZ3gQzXZ8DRxiUIbaJJGFjZa23Omi-7OSYeCL-tqYYmbUF.xORCXj2xhMIyT_dv)

***

**Mar 18:** : Day off!

***

**Mar 23:**

* [Chapter 3 - Linear Regression](../LectureNotesSp2021/Chapter3.html) --- Take notes in Rmarkdown

* Exam 1 is Tuesday next week!

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/qTBKmQxTwpNEkDSSKZGJlsXixp4QsSQZ0M24ylI5eCni97E2QzcnXK4Oc20MXg.hJS0U-Zbo-ilm7NA)

***


**Mar 25:**

```{block, startProject_1, type='rmdoptional'}

**Project 01**

* [Project 1](../Rmarkdown/DirectionsMHP2021SP.html). 

* Submit your html and Rmd files no later than 5 pm April 8th.
```

* In class **quiz 07**

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/WcxpZhUCT-aCZO9fFre57xlZfg-fi6-b0j8TAAN3cJp9vgnWrmKje-IaCv40q2JU.OgztkINX16ZfEcHX)

***

**Mar 30:**

* In class Exam 1
* [Exam Part I]()
* [Exam Part II]()

***

**April 01:**

* [Chapter 5 - Resampling Methods](../LectureNotesSp2021/Chapter5.html) --- Take notes in Rmarkdown
* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/7keID5o68CcVrnZ3Wi-N_m8AWiKE7botQHOMVdwM9qo3NMELXRk61zObtJTplhYD.msJkycVbteLQBFq9)

***

**April 06:**

* [Chapter 5 - Resampling Methods](../LectureNotesSp2021/Chapter5.html) --- Take notes in Rmarkdown
* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/EKvuHzYqsxudn32NF5uYcSQgFV2aFVgNTj9IcE3qqmD4WHRz7FFZufS07QdJiD-h.i_KpNGGfa1xx3Zh5)


***

**April 08:**

* [Chapter 5 - Resampling Methods](../LectureNotesSp2021/Chapter5.html) --- Take notes in Rmarkdown

* In class **quiz 08**

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/ITLiJLkBVETXOeMvwqondjHYiUAD_SlbRxoabTLeYtM0WC6BiRDK-VcW3ID4ln-Q.TPKvGDIBk8rexXcH)

* Project 1 due today

***


**April 13:**

* [Chapter 6 - Linear Model Selection and Regularization](../LectureNotesSp2021/Chapter6.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/NhbmOuhnojn9YxBz_Dz03kJiTKU0N5EPpfG2cwxjUeenc6J8T_h9-uHxCGOLarqy.u8GlQr88ykxDHCiK)

***

**April 15:**

* [Chapter 6 - Linear Model Selection and Regularization](../LectureNotesSp2021/Chapter6.html) --- Take notes in Rmarkdown

* In class **quiz 09**

```{block,  type='rmdoptional'}
**Chapter 5 Lab**

* Start: Reproduce [Chapter 5 Lab](../Labs/LabCrossValidation.html).  

* Submit your **Chapter 5 Lab** html file and the Rmd file, no later than 5 pm April 22th.

```


* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/PfXFG_DXU29HxgOIZ5ShHXtSXOaW0AQrbQAlOh8PGfAjRmiVzJ4jZygSc9bfT364.L3zJ5T3W10ci6OaB)

***

**April 20:**

* [Chapter 6 - Linear Model Selection and Regularization](../LectureNotesSp2021/Chapter6.html) --- Take notes in Rmarkdown

* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/s3ZaHJkT12Zv5Xd8rrUpe91ufvxjIZhbPpaB3Wa1917IYNlmLGfZNyPEm5i1nv4N.Nq_yI8Clmv2W7zR6)

***

**April 22:**

* [Chapter 6 - Linear Model Selection and Regularization](../LectureNotesSp2021/Chapter6.html) --- Take notes in Rmarkdown

* In class **quiz 10**

* **Project 2:** [Start Here](../Rmarkdown/Project2_SP2021.html)

* **Turn in Project 2 Predictions**- NLT May 3rd, 10:00 am
* Send an email to the instructor using a subject of "House Data Predictions" with an attached vector (csv file) of your predictions using the data set `housedataT.csv`.  Note: your vector should contain 4229 predictions. 

* **Turn in Project 2** - NLT May 06th, 5 pm
* Make sure a single `.Rmd` and a single `.html` with the sections outlined in the [Example Paper](../BDbetaTemplate/TemplateBookDown.html) is in your `Project2` emailed to me.


* [Project 2 Leaderboard](../StudentPredictions2021ForWeb/TestError.html)

```{block,  type='rmdoptional'}
**Reminder: **

  * Exam 2, Tuesday next week
```


* [**Lecture Recordings**](https://appstate.zoom.us/rec/share/dX39Mz_4ozorh1Cy7PcXLLflGnP3yYYAt465mpyqDF30DXE97fHTQlKLaG_mXpeA.aZlJk5EcHH2lZEYy) - Project2 Instructions

***

**April 27:**

  * Exam 2


***

* [**Project 2 Help - Part 1**](https://appstate.zoom.us/rec/share/ROIzfRqvgLWop-gdGMOy-aosv3F3YDCvSfi69oF8A1THSPDEFeB6suA0yu0gkw2P.6cKvkpNA-dFqrN67)

* [**Project 2 Help - Part 2**](https://appstate.zoom.us/rec/share/Tb_LjnXHK8J07Ga0EF0i1mLAJpojXEI84Q0unklRNECYxyKvYf0zh0XsvIsiaqPn.GgtHzaf1gZvYGNhv)

<!--
**Mar 19:**
* [Download this `textbooks.bib` file](../Rmarkdown/Fall2019/textbooks.bib)
* [Chapter 3 Applied Problems](../3-15-18/ch3_applied.pdf)
<!--* [Work on Project 1](../Rmarkdown/DirectionsMHP.html)-->
<!--* [Code for class notes](../Rmarkdown/BodyTemperatures.html)

```{block, startProject1, type='rmdoptional'}

**Project 01**

* [Start Project 1](http://www.amstat.org/publications/jse/v16n2/datasets.pardoe.html) - Read the hyperlinked paper. 
* [Directions for the complete project 1](../Rmarkdown/DirectionsMHP2018.html). 
* The data set can be downloaded from http://www.amstat.org/publications/jse/datasets/homes76.dat.txt, while the code book is available from http://www.amstat.org/publications/jse/datasets/homes76.txt

* Submit your html file to github **Project 01** folder, no later than 5 pm April 3rd.
```


**Mar 21:**

* Exam 1

**Mar 26:**

* In class **quiz 07**

* Before class:
    + Read chapter 5 [ISLR](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)
    + Watch [Estimating Prediction Error and Validation Set Approach](https://www.youtube.com/watch?v=_2ij6eaaSl0) (14:01)
    + Watch [K-fold Cross-Validation](https://www.youtube.com/watch?v=nZAM5OXrktY) (13:33)
    + Watch [Cross-Validation: The Right and Wrong Ways](https://www.youtube.com/watch?v=S06JpVoNaA0) (10:07)
    
    + Watch [Lab: Cross-Validation](https://www.youtube.com/watch?v=6dSXlqHAoMk) (11:21)


* Lecture - Chapter 05 - Take Notes

<!-- * Start Project #1. Commit your final changes for Project 1 to your private repository and email the instructor your SHA prior to 10am April 05, 2018.  Use the subject line "Project 1-STT3851-Last_name First_name-SHA#" in your email. 





**Mar 28:**



* Lecture - Chapter 06 - Take Notes
<!-- [Finish Cross-Validation Hand Out](../Rmarkdown/Cross-ValidationInClassHO.html)

* Complete [Reproduce _Lab: Cross-Validation_](../Rmarkdown/LabCrossValidation.html).  Submit your html file  no later than 5 pm April 05th.





**Apr 2:**

* Before class:
    + Watch [Estimating Test Error Using Mallow’s Cp, AIC, BIC, Adjusted R-squared](https://www.youtube.com/watch?v=LkifE44myLc) (14:06)
    + Watch [Estimating Test Error Using Cross-Validation](https://www.youtube.com/watch?v=3p9JNaJCOb4) (8:43)
* [Notes on Credit Problem](../Rmarkdown/CreditProblemMore.html)
<!--* Commit your final changes for Project 1 to your private repository and email the instructor your SHA prior to 10am April 05, 2018.  Use the subject line "Project 1-STT3851-Last_name First_name-SHA#" in your email.


* Lecture - Chapter 06 - Take Notes
* In class **quiz 08**

<!--* Start Project 2 
* [Example Template Directory](https://github.com/STAT-ATA-ASU/STT3851Spring2016/blob/gh-pages/BDbetaTemplate)
* Use the [housedata.csv](https://github.com/STAT-ATA-ASU/STT3851Spring2016/raw/gh-pages/Data/housedata.csv) file - See [King County Housing Data](../Rmarkdown/KingCounty.html) 




**Apr 4:**

```{block, startLab3, type='rmdoptional'}
**Lab 03**

* Start: [Reproduce _Lab: Cross-Validation_](../Rmarkdown/LabCrossValidation.html)  

* Submit your html file to github **Lab 3** folder, no later than 5 pm Apr 11.

```

* Before class:
    + Watch [Linear Model Selection and Best Subset Selection](https://www.youtube.com/watch?v=91si52nk3LA) (13:44)
    + [Forward Stepwise Selection](https://www.youtube.com/watch?v=nLpJd_iKmrE) (12:26)
    + [Backward Stepwise Selection ](https://www.youtube.com/watch?v=NJhMSpI2Uj8) (5:26)


* Lecture - Chapter 06 - Take Notes



**Apr 9:**

* Before class:

    + Watch [Shrinkage Methods and Ridge Regression](https://www.youtube.com/watch?v=cSKzqb0EKS0) (12:37)
    + Watch [The Lasso](https://www.youtube.com/watch?v=A5I1G1MfUmA) (15:21)
    + Watch [Tuning Parameter Selection for Ridge Regression and Lasso](https://www.youtube.com/watch?v=xMKVUstjXBE) (5:27)


* Lecture - Chapter 06 - Take Notes

* In class **quiz 09**


**Apr 11:**

* Before class review [Book Down](https://bookdown.org/yihui/bookdown/)
* Before class 
    + Watch [Dimension Reduction](https://www.youtube.com/watch?v=QlyROnAjnEk) (4:45)
    + Watch [Principal Components Regression and Partial Least Squares ](https://www.youtube.com/watch?v=eYxwWGJcOfw) (15:48)
   
   
* Lecture - Chapter 06 - Take Notes




**Apr 16:**

* Before class
    + Watch [Lab: Best Subset Selection](https://www.youtube.com/watch?v=3kwdDGnV8MM) (10:36)
    + Watch [Lab: Forward Stepwise Selection and Model Selection Using Validation Set](https://www.youtube.com/watch?v=mv-vdysZIb4) (10:32)
    + Watch [Lab: Model Selection Using Cross-Validation](https://www.youtube.com/watch?v=F8MMHCCoALU) (5:32)
    + Watch [Lab: Ridge Regression and Lasso ](https://www.youtube.com/watch?v=1REe3qSotx8) (16:34)
    
* Lecture - Chapter 06 - Take Notes



**Apr 18:**

```{block, startProject2, type='rmdoptional'}

**Project 02**

* Project 2: [Start Here](../Rmarkdown/Project2.html)

* Submit your html file to github **Project 02** folder, no later than 5 pm Apr 30.
```



**~~Apr 22-23:~~ No Class - State Holidays**

**Apr 25:**

* Lecture - Chapter 06 - Take Notes  
* In class **quiz 10**
* Work on Project 2



**Apr 30:**

* Exam 2

* Turn in Project 2 - NLT May 02, 10 am
* Make sure a single `.Rmd` with the sections outlined in the [Example Paper](../BDbetaTemplate/TemplateBookDown.html) is in your `Project2` directory under your private course repository.
* Send an email to the instructor using a subject of "House Data Predictions" with an attached vector (csv file) of your predictions using the data set `housedataTEST.csv`.  Note: your vector should contain 4229 predictions. 

* [Project 2 Leaderboard](../StudentPredictions2018ForWeb/TestError.html)


**May 2:**

* Reading Day




* [data file 1](SMELTPOT.txt)
* [data file 2](STREETVN.txt)

-->

* [Auto Data .txt](Auto.txt)
* [Auto Data .csv](Auto.csv)

# [Home Page](http://Lasanthi-ASU.github.io/STT3851ClassRepo/) - [Syllabus](https://lasanthi-asu.github.io/STT3851ClassRepo/Syllabus/STT3851Spring2021Syllabus.html) {-}  



