---
title: "Exam 1 grades"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    highlight: textmate
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(ggplot2)
```


# STT 3851 Exam 1 grades Spring 2023.{-}

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(plotly)
library(ggplot2)
Class2 <- c(60,91,80,100,92,86,69,82,92,84,73,80,72,86,63,64)


p2 <- ggplot(data = data.frame(Class2), aes(x = Class2)) + 
  geom_density(fill = "orchid4") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class2), linetype="dotted") +
  annotate("text",x=median(Class2)+1,y=0.01,label="Exam Average = 81",hjust=0)

ggplotly(p2)


p3 <- ggplot(data = data.frame(Class2), aes(y = Class2)) + 
  geom_boxplot(fill = "pink") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") 

p3


library(dplyr)
library(knitr)

q <- quantile(Class2)

q <- as.matrix(q)
rownames(q) <- c("Min", "Q1", "Median", "Q3", "Max")
colnames(q) <- c("Value")
kable(q)


```









